openapi: 3.0.1
info:
  title: I_Entitlement_Management_EU
  description: |
    This interface provides access to the service **Entitlement Management** of a personal health 
    record for insurants. The provided operations allow the management of entitlement for EU-access.<br/>

    **General conditions**:</br> 
    For all operations if applicable:
    - a section _Client_ in operation descriptions covers recommendations (informative) for clients.
    - a section _Provider_ in operation descriptions covers requirements for the server side. 
    - error responses may be extended by helpful information about the error condition in _errorDetail_

    **Prerequisites**:</br>
    The Health Record System shall provide 
    - name
    - role ((profession-)oid)
    - identifier (telematik-id or kvnr)
    - indication of a valid entitlement 
    
    of the current user (requestor) for evaluation in operations.

    Operations mandating a valid entitlement implicitly mandate use of a VAU-channel,
    a valid ID-Token, a registered device and a valid entitlement. If one of these conditions is not met, then the response
    of the (aborted) operation shall always be '403': 'notEntitled'. 

    **User Agent**:</br>
    The user agent information (x-useragent) is part of any request, even if 
    not essentially required for the operation (e.g. raw-data collection), and
    may be considered for provider internal use. 

    **Log-Entries**
    Whenever a _Postcondition_ mandates a log-entry, this entry shall contain
    data as defined in A_24987*.

  contact:
    name: gematik GmbH
    url: 'http://www.gematik.de'

  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'

  version: 0.0.1 

  # version history:
  # ----------------
 
  # version 0.0.1
  #   - initial version

servers:
  - url: https://epa-hst1.prod.epa4all.de

tags:
  - name: Entitlements-EU
    description: |
     **Entitlement-EU of a european country resident healthcare provider**

     The objective of Entitlement-EU is to enable a healthcare provider in a European foreign country to 
     access a german insurant's health record.

     Accesses by the healthcare provider from a European foreign country to an insurant's health record do not 
     occur directly but through an intermediary service, the National Contact Point eHealth (NCPeH).

     Therefore, the entitlement process considers two aspects:
     - the creation of the entitlement for the NCPeH
     - the generation of a specific access code for the healthcare provider

     The specific access code is communicated by the insurant to the healthcare provider in the European foreign 
     country during a treatment situation. By entering the access code into the provider's system and using the 
     intermediary NCPeH, it is ensured that access to the insurant's health record is exclusively granted to this
     healthcare provider.
     
     The Entitlement-EU for the NCPeH is not granted generally but always specifically for the European country 
     in which a healthcare provider is to be consulted (e.g. NCPeH-France). The necessary identifier (telematik-id)
     of such NCPeH for entitlement shall be retrieved by the client using the VZD FHIR directory.
     
     Example:
     The (german) insurant needs medical treatment of a particular healthcare provider in France:
     1. Insurant searches the VZD Directory for NCPeH-France for Entitlement by use of ePA-FdV
     2. The ePA-FdV uses the VZD Information to generate a suitable jwt for entitlement and also generates 
     an access code. 
     3. The ePA-FdV uses both, jwt and access code, with the setEntitlementEu operation. This entitles the NCPeH (France)
     and keeps the access code for later validation.
     4. The insurant uses the ePA-FdV to display the access code to the healthcare provider 
     in France.
     5. The healthcare provider enters the access code in his local system and has now access to certain operations 
     and data of the insurant's health record via the entitled NCPeH within the validity period of the entitlement.

     **Allowed usergroups for Entitlement-EU:**
     Entitlement-EU can only be set for the role oid_ncpeh. For entitlement of other roles refer to the regular operation _setEntitlement_.</br>
     Entitlements (EU) can only be granted by the insurant itself (not by representatives)
     
     **The _validTo_ attribute:**</br>
     The _validTo_ attribute of an Entitlement-EU is set by the health record system and includes always a fixed validity period of one hour.

     **Scope of Entitlement:**</br>
     An entitled NCPeH/healthcare provider has limited access to the document categories (according to legal policy) of 
     the xds document service.

     **Constraints:**</br>
     A health record can have a maximum of one Entitlement-EU with one associated access code at a time. Therefore it is not possible
     to entitle more than one european country or to have an Entitlement-EU with more than one valid access code. </br>
     The validity period of an Entitlement-EU can not be extended. (If further access is required by the healthcare provider
     a new Entitlement-EU, including a new access code, shall be set by the insurant/ePA-FdV.) 

     This interface (I_Entitlement_Management_EU) provides the NCPeH specific operations for entitlement only. A client 
     shall use the operations of I_Entitlement_Management for the purpose of viewing granted entitlements, including Entitlment (EU),
     or premature deletion of entitlements, including Entitlement-EU.

paths:
  /epa/basic/api/v1/ncpeh/entitlements:
    parameters:
      - $ref: '#/components/parameters/insurantid'
      - $ref: '#/components/parameters/useragent'
    post:
      tags:
        - Entitlement-EU
      operationId: setEntitlementEu
      summary: (setEntitlementEu) Set a single entitlement for a specific NCPeH
      description: |
       This operation sets a new entitlement for a National Contact Point eHealth (NCPeH).
       The entitlement refers to a country specific identity of a NCPeH, identified by a telematik-id 
       of a country specific sm-b and is associated to a unique access code for a healthcare provider.
       The entitlement grants general access to a health record for one hour.</br>
       This operation is limited to the insurant (health record owner) with role oid_versicherter.


       **Client (ePA-FdV)**:</br>
       A client shall use _setEntitlementEu_ only for healthcare treament situations in foreign european 
       countries (i.e. not in Germany).
       The client shall present the access code associated to the entitlement and protecting any health record 
       service operation to the healthcare provider.
       
       **Provider**:</br>
       Requests to entitle a role other than oid_ncpeh shall be rejected.
       The received JWT shall be passed to the HSM for entitlement verification, using rule _tbd_.
       The validity of an existing entitlement will be extended by setting a new entitlement.
       In case of one existing valid entitlement no further entitlements with role oid_ncpeh are allowed.

       The HSM shall verifiy the JWT signature, _actorID_, _kvnr_ (associated health record) and claims
       in a CMAC secured result _actorId_, _kvnr_ and _validTo_. _validTo_ shall be set to a point in time
       exactly one hour in the future of current time.

       The CMAC secured result shall be completed with the following data:
       - _oid_ of the entitled NCPeH (from JWT, shall always be oid_ncpeh)
       - _displayName_ of the entitled NCPeH (the county-specific NCPeH's name, from JWT)
       - _issued-at_ current system time
       - _issued-actorId_ of requestor (from request context, shall always be kvnr of health record owner)
       - _issued-displayName_ of requestor (from request context, shall always be displayName of health record owner)
       - _accessCode_ (from request body)
       
       The completed entitlement shall be stored, encrypted by SecureAdminStorageKey of the health record.</br>
       Existing entitlements (same _oid_) shall automatically be replaced by the new, valid entitlement. There shall
       be a maximum of one valid entitlement with oid_ncpeh granted for a particular health record.

       The completed entitlement shall NOT be stored and cause operation abortion in cases:
       - request claims _actorId_ which is _actorId_ of a static entitlement
       - request claims _oid_ != oid_ncpeh
       - requestor is not insurant
       - request claims additional other _actorID_ to an existing _actorID_ (another entitlement ist already existing) 
       
       | Conditions | Status code | Error code | Remarks |
       |------------|-------------|------------|---------|
       | Successful operation | 201 |||
       | Request does not match schema | 400 | malformedRequest ||
       | Requestor is not the insurant | 403 | invalidUser ||
       | HSM verification failed | 403 | invalidToken ||
       | Health record does not exist | 404 | noHealthRecord | _insurantid_ unknown |
       | Health record is not in state ACTIVATED | 409 | statusMismatch | (see 'Retry interval') |
       | request claims _actorId_ which is _actorId_ of a static entitlement | 409 | invalidActorId ||
       | request claims _actorId_ == kvnr | 409 | requestMismatch ||
       | request claims _oid_ != oid_ncpeh | 409 | requestMismatch ||
       | request claims another_actorId_ | 409 | moreThanOneActorId ||
       | Any other error | 500 | internalError | (see 'Retry interval') |

       </br>
       | Postconditions                        | Remarks |
       |---------------------------------------|---------|
       | The valid and completed entitlement is stored in SecureDataStorage | a possible existing entitlement with same _oid_ is replaced |
       | A log-entry for the operation exists | all operation results |
       | The raw-data of the operation is collected and associated to _useragent_ | for any operation result according to gemSpec_Perf UC_A2.2 and UC_A2.5 |

      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/EntitlementEuRequestType'
            examples:
              france:
                $ref: '#/components/examples/Set_SingleEntitlementEuFrance'
              spain:
                $ref: '#/components/examples/Set_SingleEntitlementEuSpain'

      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntitlementEuResponseType'
              examples:
                france:
                  $ref: '#/components/examples/Response_SingleEntitlementFrance'
                spain:
                  $ref: '#/components/examples/Response_SingleEntitlementSpain'
        '400':
          $ref: '#/components/responses/Error400BadRequest'
        '403':
          $ref: '#/components/responses/Error403Forbidden'
        '404':
          $ref: '#/components/responses/Error404NotFound'
        '409':
          $ref: '#/components/responses/Error409Conflict'
        '500':
          $ref: '#/components/responses/Error500InternalError'

  /epa/basic/api/v1/ncpeh/entitlements/{actorId}:
    parameters:
      - $ref: '#/components/parameters/insurantid'
      - $ref: '#/components/parameters/actorId'
      - $ref: '#/components/parameters/useragent'
    get:
      tags:
        - Entitlements-EU
      operationId: getAccessCode
      summary: (getAccessCode) Get the access code associated to NCPeH entitlement
      description: |
        Get the access code of the granted and not expired Entitlement-EU of the health record.</br>
        This operation is limited to the insurant (health record owner) with role oid_versicherter.

        **Client**:</br>
        A client may use this operation to recall the access code of a previously set Entitlement-EU

        **Provider**:</br>
        The response shall contain the access code associated to _actorId_.

        The operation shall not succeed in case the stored entitlement does not claim _oid_ = oid_ncpeh

        | Conditions | Status code | Error code | Remarks |
        |------------|-------------|------------|---------|
        | Successful operation | 200 |||
        | Request does not match schema | 400 | malformedRequest ||
        | Requestor is not the insurant | 403 | invalidUser ||
        | Health record does not exist | 404 | noHealthRecord | _insurantid_ unknown |
        | Entitlement (_actorid_) does not exist | 404 | noResource ||
        | Entitlement claims _oid_ other thn oid_ncpeh | 409 | invaildOid ||
        | Health record is not in state ACTIVATED | 409 | statusMismatch ||
        | Any other error | 500 | internalError ||

         </br>
        | Postconditions                        | Remarks |
        |---------------------------------------|---------|
        | none ||

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessCodeNcpehResponseType'
              examples:
                france:
                  summary: Access code of entitlement for France
                  value:
                    actorId: 9-883110000035981
                    displayName: 'Frankreich (FR)'
                    accessCode: 'A2C4E6'
                spain:
                  summary: Access code of entitlement for Spain
                  value:
                    actorId: 9-883110000044264
                    displayName: 'Spanien (ES)'
                    accessCode: '0xH48F'
        '400':
          $ref: '#/components/responses/Error400BadRequest'
        '403':
          $ref: '#/components/responses/Error403Forbidden'
        '404':
          $ref: '#/components/responses/Error404NotFound'
        '409':
          $ref: '#/components/responses/Error409Conflict'
        '500':
          $ref: '#/components/responses/Error500InternalError'

components:
  responses:
    Error400BadRequest:
      description: Bad Request.
      content:
        application/json:
          example:
            errorCode: malformedRequest
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error403Forbidden:
      description: Forbidden.
      content:
        application/json:
          example:
            errorCode: invalidUser
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error404NotFound:
      description: Not found.
      content:
        application/json:
          example:
            errorCode: noResource
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error409Conflict:
      description: Conflict.
      content:
        application/json:
          examples:
            statusMismatch:
              value:
                errorCode: statusMismatch
            requestMismatch:
              value:
                errorCode: requestMismatch
            resourceMismatch:
              value:
                errorCode: resourceMismatch
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error500InternalError:
      description: Internal Server Error
      content:
        application/json:
          example:
            errorCode: internalError
          schema:
            $ref: '#/components/schemas/ErrorType'

  parameters:
    insurantid:
      name: x-insurantid
      in: header
      description: Health Record Identifier.
      required: true
      schema:
        $ref: '#/components/schemas/InsurantIdType'
    useragent:
      name: x-useragent
      in: header
      description: user agent information
      required: true
      schema:
        $ref: '#/components/schemas/UserAgentType'
    actorId:
      name: actorId
      in: path
      description: TelematikID
      required: true
      schema:
        $ref: '#/components/schemas/TelematikIdType'

  schemas:
    KvnrType:
      type: string
      pattern: '^[A-Z]{1}\d{9}$'
      example: Z123456789
    TelematikIdType:
      type: string
      pattern: '^[1-9][0-9]?-[\x21-\x7E]+$'
      maxLength: 128
      example: 2-883110000118994
    OidType:
      description: A professionOID
      type: string
      pattern: '([0-2])((\.0)|(\.[1-9][0-9]*))*$'
      example: '1.2.276.0.76.4.50'
    DisplayNameType:
      description: A readable name
      type: string
      example: 'Praxis Dr. Annamaria Heckhausén'
    ValidToType:
      description: End of validity
      type: string
      format: date-time
      example: 2025-01-01T18:00:00Z
    AccessCodeType:
      description: Random access code (6 characters)
      type: string
      pattern: ^[A-Za-z0-9]{6}$
    EntitlementEuRequestType:
      description: Request for a Entitlement-EU
      type: object
      properties:
        jwt:
          description: |
            "A JSON Web Token (JWT) with following format build according to RFC-7515:</br>
            base64url (protected_header) + '.' + base64url (payload) + '.' + base64url (signature)"</br>
            - protected_header contains:
              - "typ": "JWT"
              - "alg": "ES256" 
              - "x5c": signature certificate (C.CH.SIG)
            - payload claims:
              - "iat": issued at timestamp
              - "exp": expiry timestamp (always iat + 20min)
              - "insurantid": the health record identifier this entitlement is assoctiated to
              - "actorId": telematik-td (of counntry-specific NCPeH)
              - "oid": value of professionOID (shall be oid_ncpeh)
              - "displayName": name according to actorId
            - signature contains token signature
          type: string
          format: application/jwt
          pattern: ^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$
          example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsIng1YyI6ImNlcnRpZmljYXRlIGMuY2guc2lnIn0.eyJpYXQiOjE3MzY4OTkyMDAsImV4cCI6MTczNjkwMDQwMCwiaW5zdXJhbnRpZCI6IkExMjM0NTY3ODkiLCJhY3RvcmlkIjoiOS04ODMxMTAwMDAwMzU5ODEiLCJvaWQiOiIxLjIuMjc2LjAuNzYuNC4yOTIiLCJkaXNwbGF5TmFtZSI6IkZyYW5rcmVpY2ggKEZSKSJ9.e3NpZ25hdHVyZU92ZXJIZWFkZXJBbmRQYXlsb2FkfQ"
        accessCode:
          $ref: '#/components/schemas/AccessCodeType'
      required:
        - jwt
        - accessCode
    AccessCodeNcpehResponseType:
      description: The access code associated to the entitlement.
      type: object
      properties:
        actorId:
          $ref: '#/components/schemas/TelematikIdType'
        displayName:
          $ref: '#/components/schemas/DisplayNameType'
        accessCode:
          $ref: '#/components/schemas/AccessCodeType'
      required:
        - accessCode
    EntitlementEuResponseType:
      description: Properties of one ncpeh entitlement
      type: object
      required:
        - actorId
        - oid
        - displayName
        - accessCode
        - validTo
      properties:
        actorId:
          $ref: '#/components/schemas/TelematikIdType'
        oid:
          $ref: '#/components/schemas/OidType'
        displayName:
          $ref: '#/components/schemas/DisplayNameType'
        validTo:
          $ref: '#/components/schemas/ValidToType'
        issued:
          type: object
          required:
            - at
            - actorId
            - displayName
          properties:
            at:
              description: Creation time timestamp
              type: string
              format: date-time
              example: 2025-01-01T18:00:00Z
            actorId:
              $ref: '#/components/schemas/KvnrType'
            displayName:
              $ref: '#/components/schemas/DisplayNameType'
        accessCode:
          $ref: '#/components/schemas/AccessCodeType'
    UserAgentType:
      description: "Information about client software with: ClientId(20 characters) + / + VersionNumber (1 to 15 characters)."
      type: string
      pattern: '^[a-zA-Z0-9\-]{1,20}\/[a-zA-Z0-9\-\.]{1,15}$'
      example: CLIENTID1234567890AB/2.1.12-45
    InsurantIdType:
      type: string
      description: |-
        The health record identifier. 
        For today the record identifier equals the insurant id (kvnr).
      pattern: '^[A-Z]{1}\d{9}$'
      example: Z123456789
    ErrorType:
      description: Error object with additional information about the occurred error
      type: object
      properties:
        errorCode:
          description: Error condition specifier
          type: string
        errorDetail:
          description: Additional details regarding the error condition (if applicable)
          type: string
      required:
        - errorCode

  examples:
    Set_SingleEntitlementEuFrance:
      summary: Entitlement-EU country France.
      value:
        jwt: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsIng1YyI6ImNlcnRpZmljYXRlIGMuY2guc2lnIn0.eyJpYXQiOjE3MzY4OTkyMDAsImV4cCI6MTczNjkwMDQwMCwiaW5zdXJhbnRpZCI6IkExMjM0NTY3ODkiLCJhY3RvcmlkIjoiOS04ODMxMTAwMDAwMzU5ODEiLCJvaWQiOiIxLjIuMjc2LjAuNzYuNC4yOTIiLCJkaXNwbGF5TmFtZSI6IkZyYW5rcmVpY2ggKEZSKSJ9.e3NpZ25hdHVyZU92ZXJIZWFkZXJBbmRQYXlsb2FkfQ'
        accessCode: 'A2C4E6'
    Set_SingleEntitlementEuSpain:
      summary: Entitlement-EU country Spain.
      value:
        jwt: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsIng1YyI6ImNlcnRpZmljYXRlIGMuY2guc2lnIn0.eyJpYXQiOjE3MzY5MDA0MDAsImV4cCI6MTczNjkwMTYwMCwiaW5zdXJhbnRpZCI6IkExMjM0NTY3ODkiLCJhY3RvcmlkIjoiLTg4MzExMDAwMDA0NDI2NCIsIm9pZCI6IjEuMi4yNzYuMC43Ni40LjI5MiIsImRpc3BsYXlOYW1lIjoiU3BhbmllbiAoRVMpIn0.e3NpZ25hdHVyZU92ZXJIZWFkZXJBbmRQYXlsb2FkfQ'
        accessCode: '0xH48F'

    Response_SingleEntitlementFrance:
      summary: Entitlement-EU for country France.
      value:
          actorId: 9-883110000035981
          oid: 1.2.276.0.76.4.292
          displayName: 'Frankreich (FR)'
          validTo: 2025-01-01T23:00:00Z
          issued:
            at: 2025-01-01T22:00:00Z
            actorId: X999999999
            displayName: 'Name of health record owner'
          accessCode: 'A2C4E6'
    Response_SingleEntitlementSpain:
      summary: Entitlement-EU for country Spain.
      value:
        actorId: 9-883110000044264
        oid: 1.2.276.0.76.4.292
        displayName: 'Spanien (ES)'
        validTo: 2025-10-04T15:03:00Z
        issued:
          at: 2025-10-04T14:03:00Z
          actorId: X999999999
          displayName: 'Name of health record owner'
        accessCode: '0xH48F'

